#!/bin/bash
## Estableciendo usuario ssh en archivo sudoers, se comprueba antes si ya está metido en caso de que el array se reinicie
CHECK_SUDOERS=$(grep -c 'ssh  ALL=(ALL)  ALL' /etc/sudoers)
if [[ $CHECK_SUDOERS == 0 ]]
then
    echo 'ssh  ALL=(ALL)  ALL' >> /etc/sudoers
fi

## Copiar claves SSH de la memoria flash a la ruta de claves del usuario, se comprueba antes si ya está metido en caso de que el array se reinicie
CHECK_AUTH_KEYS=$(find /home/ssh/.ssh/ -name authorized_keys | wc -l)
if [[ $CHECK_AUTH_KEYS == 0 ]]
then
cp /boot/config/ssh/ssh/authorized_keys /home/ssh/.ssh/
chmod 644 /home/ssh/.ssh/authorized_keys
chown ssh /home/ssh/.ssh/authorized_keys
chgrp users /home/ssh/.ssh/authorized_keys
fi
