#!/bin/bash
## Setting up the user in sudoers file, check as well if the user is already in the sudoers file due to script cron to array start
CHECK_SUDOERS=$(grep -c 'ssh  ALL=(ALL)  ALL' /etc/sudoers)
if [[ $CHECK_SUDOERS == 0 ]]
then
    echo 'ssh  ALL=(ALL)  ALL' >> /etc/sudoers
fi

## Copies the ssh key from flash to user's key folder, check as well if the key is already in the user's key folder
CHECK_AUTH_KEYS=$(find /home/ssh/.ssh/ -name authorized_keys | wc -l)
if [[ $CHECK_AUTH_KEYS == 0 ]]
then
cp /boot/config/ssh/ssh/authorized_keys /home/ssh/.ssh/
chmod 644 /home/ssh/.ssh/authorized_keys
chown ssh /home/ssh/.ssh/authorized_keys
chgrp users /home/ssh/.ssh/authorized_keys
fi
